spring:
  datasource:
    url: jdbc:mysql://localhost/new_game
    username:
    password:
  redis:
    host: localhost
    port:
    password: root
  mvc:
    view:
      suffix: .html
      prefix: /
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.example.springbootnewgame.mapper